# fly.toml app configuration file generated for wandering-star-1774 on 2023-09-09T16:35:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-star-1774"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
