POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNwYXJ2MiIsImlkIjoiNjU0OTNhY2ZkNDMxM2VjYzJlZTg4ZWU4IiwiaWF0IjoxNjk5NzA3MTM3fQ.n0lT80qjI_jo3xjr3T8Wm7VbDa5PUik0wqg9Gp4Oxew

{
"author":"Anna",
"title":"With token sat 1",
"url":"testurl"
}